executor: KubernetesExecutor

iamges:
	airflow:
		repository: <>

postgressql:
  enabled: true
  image:
		registry: <>
		repository: <>
		tag: 16.1.0
	imagePullSecrets:
		- name: <>
	auth:
		username: airflow
		database: airflow
		passwordKey: airflow-passwordKey
		postgresPasswordKey: postgres-passwordKey
	existingSecret: airflow-db-creds
	
redis:
	enabled: false
	
webserver:
	service:
		type: ClusterIP
	resources:
		requests:
			memory: "512Mi"
			cpu: "250m"
		limits:
			memory: "1Gi"
			cpu: "500m"
		waitForMigrations:
			enabled: true
		startupProbe:
			timeoutSeconds: 40
			scheme: HTTP
			initialDelaySeconds: 20
			periodSeconds: 10
			failureThreshold: 30


scheduler:
	enabled: true
	resources:
		requests:
			memory: "512Mi"
			cpu: "250m"
		limits:
			memory: "1Gi"
			cpu: "500m"	
		waitForMigrations:
			enabled: true

logs:
	persistence:
		enabled: true
		size: "1Gi"
        
extraObjects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: create-airflow-admin
      namespace: britac
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: create-admin
              image: apache/airflow:2.10.5
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: airflow-admin-creds
              command: ["/bin/bash", "-c"]
              args:
                - |
                  airflow db upgrade &&
                  airflow users create \
                    --username "$AIRFLOW_ADMIN_USERNAME" \
                    --firstname Admin \
                    --lastname User \
                    --role Admin \
                    --email "$AIRFLOW_ADMIN_EMAIL" \
                    --password "$AIRFLOW_ADMIN_PASSWORD"
        
